package com.whmnrc.cdy.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whmnrc.cdy.bean.RadonBean;

import com.whmnrc.cdy.db.RadonBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig radonBeanDaoConfig;

    private final RadonBeanDao radonBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        radonBeanDaoConfig = daoConfigMap.get(RadonBeanDao.class).clone();
        radonBeanDaoConfig.initIdentityScope(type);

        radonBeanDao = new RadonBeanDao(radonBeanDaoConfig, this);

        registerDao(RadonBean.class, radonBeanDao);
    }
    
    public void clear() {
        radonBeanDaoConfig.getIdentityScope().clear();
    }

    public RadonBeanDao getRadonBeanDao() {
        return radonBeanDao;
    }

}
